# Only bundled skill assets are extracted; the CoCo executable is not installed.
{ pkgs, adaptations }:
let
  version = "1.1.27+200623.07dcb388081e";
  archiveRoot = "coco-${version}-linux-amd64";
  source = pkgs.fetchurl {
    url = builtins.replaceStrings [ "+" ] [ "%2B" ]
      "https://sfc-repo.snowflakecomputing.com/cortex-code-cli/a4643c4278/${version}/${archiveRoot}.tar.gz";
    sha256 = "d1a85cf7e5ab946c560334944fa5cc5a74e12d468139f9329bbef3261b8cef69";
  };
in
pkgs.runCommand "snowflake-skills-${version}" {
  nativeBuildInputs = [ pkgs.gnutar pkgs.gzip pkgs.patch pkgs.gawk ];
} ''
  mkdir -p "$out"
  tar -xzf ${source} --strip-components=2 -C "$out" '${archiveRoot}/bundled_skills'
  patch --directory="$out" --strip=1 --fuzz=0 --batch < ${adaptations}/catalog.patch
  bash ${../tests/test_snowflake_skills.sh} ${../scripts/adapt-snowflake-skills.sh}
  bash ${../scripts/adapt-snowflake-skills.sh} "$out" ${adaptations}/notice.md
  cp ${adaptations}/CURSOR_ADAPTATION.md "$out/CURSOR_ADAPTATION.md"
  cat > "$out/SOURCE.md" <<'EOF'
  # CoCo bundled skills catalog (host-adapted)

  Source: Snowflake Cortex Code CLI ${version}, linux-amd64 bundled_skills/.
  The archive hash is maintained in public dotfiles.
  Host-specific customizations come from the private dotfiles input.
  This catalog is generated by Nix and is not vendored in either repository.
  See CURSOR_ADAPTATION.md for the host tool mapping.
  EOF
''
