# Only bundled skill assets are extracted; the CoCo executable is not installed.
{ pkgs, adaptations }:
let
  version = "1.1.104+041358.66de1c44636f";
  archiveRoot = "coco-${version}-linux-amd64";
  source = pkgs.fetchurl {
    url = builtins.replaceStrings [ "+" ] [ "%2B" ]
      "https://sfc-repo.snowflakecomputing.com/cortex-code-cli/a4643c4278/${version}/${archiveRoot}.tar.gz";
    sha256 = "149d0c225a174e0efcf384031c4d2849a97f09b43c10bb3427ce271e5fafd372";
  };
in
pkgs.runCommand "snowflake-skills-${version}" {
  nativeBuildInputs = [ pkgs.gnutar pkgs.gzip ];
} ''
  mkdir -p "$out"
  tar -xzf ${source} --strip-components=2 -C "$out" '${archiveRoot}/bundled_skills'
  cp ${adaptations}/HOST_ADAPTATION.md "$out/HOST_ADAPTATION.md"
  cat > "$out/SOURCE.md" <<'EOF'
  # CoCo bundled skills catalog

  Source: Snowflake Cortex Code CLI ${version}, linux-amd64 bundled_skills/.
  The archive hash is maintained in public dotfiles.
  Upstream skill files are preserved without modification.
  Host-specific guidance comes from the private dotfiles input.
  This catalog is generated by Nix and is not vendored in either repository.
  Read HOST_ADAPTATION.md before using the upstream instructions.
  EOF
''
